config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#homepage'
 
  resources :groups, only: [:index, :new, :create] do 
    resources :expenses, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true, length: { maximum: 250 }
  validates :amount, presence: true, numericality: { greater_than: 0 }

  belongs_to :author, class_name: 'User'

  has_many :group_expenses, class_name: 'GroupExpense', dependent: :destroy
  has_many :groups, through: :group_expenses, dependent: :destroy
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :icon

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true

  belongs_to :author, class_name: 'User'
  has_many :group_expenses, class_name: 'GroupExpense', dependent: :destroy
  has_many :expenses, through: :group_expenses

  def total_amount
    expenses.sum(:amount)
  end
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 250 }
  validates :email, presence: true

  has_many :groups, foreign_key: 'author_id', dependent: :destroy
  has_many :expenses, foreign_key: 'author_id', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @group_expenses = @group.group_expenses
    @expenses = Expense.joins(:group_expenses, :groups)
      .where('expenses.id = group_expenses.expense_id')
      .where('groups.id = group_expenses.group_id')
      .where('groups.id = ?', params[:group_id]).order('expenses.created_at DESC')
  end

  def new
    @expense = Expense.new
    @groups = current_user.groups
  end

  def create
    @expense = Expense.new(name: params[:name], amount: params[:amount], author_id: params[:author_id])

    if @expense.save
      group_expense = GroupExpense.new(group_id: params[:group], expense_id: @expense.id)
      group_expense.save
      flash[:success] = 'Transaction was successfully.'
      redirect_to group_expenses_path(params[:group])
    else
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :author_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @user = current_user
    @groups = current_user.groups.all
  end

  def new
    @group = Group.new
  end

  def create
    @user = current_user
    @group = current_user.groups.new(group_params)
    if @group.save
      flash[:success] = 'Category created successfully.'
      redirect_to groups_path
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon.name, :author_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/index.html.erb
<div class="container flex flex-col justify-between h-screen bg-slate-100 px-0">
  <div class="flex-1 m-0">
    <div class="flex justify-between items-center bg-blue py-4 px-3">
      <%= link_to groups_path do %>
        <span class="text-white" style="font-size:24px;">&#10229;</span>
      <% end %>
      <span class="uppercase text-white font-medium">TRANSACTIONS</span>
      <%= button_to "", class: "bg-blue focus:border-white" do %>
        <i class="fas fa-search text-white p-2" style="font-size:24px;"></i>
      <% end %>
    </div>
    <div class="list-group-item shadow-sm justify-between items-center mb-3">
      <div class="flex justify-start px-3 gap-2">
        <%= image_tag url_for(@group.icon),
        alt: @group.name,
        class: "object-fit-fill rounded-0 float-left h-16 w-16" %>
        <div class="flex flex-1 justify-between w-full py-4 px-1">
          <span class="items-center font-medium"><%= @group.name %></span>
          <span class="items-center font-medium"><%= number_to_currency(@group.total_amount) %></span>
        </div>
      </div>
    </div>
    <ul class="list-group rounded-0 px-3 mt-3">
      <% @expenses.each do |expense| %>
        <li class="list-group-item bg-white drop-shadow-lg justify-between items-center mb-3">
          <div class="flex justify-between items-center bg-white w-full p-4 gap-4">
            <span class="flex-1 text-left"><%= expense.name %></span>
            <span class="text-right"><%= number_to_currency(expense.amount) %></span>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="w-full flex bg-bubble text-white rounded-0 m-0 p-4">
    <%= link_to "Add New Transaction",
    new_group_expense_path(@group),
    class:
      "bg-bubble font-medium text-center border border-white flex-1 text-white rounded-0  py-2 m-0" %>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="container d-flex flex-column justify-content-between vh-100 bg-light px-0">  
  <%= form_with url: group_expenses_path, locale: true, method: :post  do |f| %>
   <div class="flex justify-between items-center bg-blue py-4 px-2">
      <%= link_to group_expenses_path do %>
        <span class="text-white" style="font-size:24px;">&#10229;</span>
      <% end %>
      <span class="uppercase text-white">New Transaction</span>
      <%= f.submit "Save", class: "text-white p-1 font-semibold" %>  
    </div>
    <fieldset class="flex flex-col">
      <%= f.text_field :name, placeholder: "Name", required: true, class: "form-control rounded-0 shadow-none" %>
      <%= f.number_field :amount, placeholder: "Amount", required: true, class: "form-control rounded-0 shadow-none" %>
      <div class= "form-control rounded-0 px-3 py-2 shadow-none w-full border border-current gap-2">
      <%= f.label :Category %>
        <%= f.select :group, current_user.groups.map { |category| [category.name, category.id] }, required: true, class: ""%>
      </div>
      <%= f.hidden_field :author_id, value: current_user.id %>
    </fieldset>
  <% end %>  
</div>

app/views/groups/index.html.erb
<div class="container flex flex-col justify-between h-screen bg-slate-100 px-0">
  <div class="relative basis-1 m-0">
    <div class="flex justify-between items-center bg-blue py-4 px-4">
       <%= render "shared/header" %>
      <span class="uppercase text-white font-medium">categories</span>
      <%= button_to "", class: "bg-blue focus:border-white" do %>
        <i class="fas fa-search text-white p-2" style="font-size:24px;"></i>
      <% end %>
    </div>
    <ul class="list-group flex flex-col bg-slate-100 gap-y-4 p-4 rounded-0">
      <% @groups.each do |group| %>  
        <li class="list-group-item shadow-lg justify-between p-3 bg-white items-center">
          <%= link_to group_expenses_path(group), class: "text-decoration-none" do %>
          <div class="flex justify-start py-0 bg-white gap-2">
           <img src="<%= url_for(group.icon) %>" alt="<%= group.name %>" class="object-fit-fill rounded-0 float-left h-16 w-16" />
            <div class="flex flex-1 justify-between w-full px-1">
              <div class="flex flex-col justify-between">
                <span class="items-center text-blue font-medium"><%= group.name %></span>
                <span><%= group.created_at.strftime("%d %b %Y") %></span>
              </div>
              <span class="items-center text-blue font-medium"><%= number_to_currency(group.total_amount) %></span>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<div class="w-full flex bg-bubble text-white rounded-0 m-0 p-4">
  <%= link_to "Add New Category", new_group_path, class: "bg-bubble font-medium text-center border border-white flex-1 text-white rounded-0  py-2 m-0" %>
</div>
</div>

app/views/groups/new.html.erb
<div class="container d-flex flex-column justify-content-between vh-100 bg-light px-0">  
  <%= form_for @group do |f| %>
   <div class="flex justify-between items-center bg-blue py-4 px-2">
      <%= link_to groups_path do %>
        <span class="text-white" style="font-size:24px;">&#10229;</span>
      <% end %>
      <span class="uppercase text-white">New Category</span>
       <%= f.submit "Save", class: "text-white p-1 font-semibold" %>  
    </div>
     <fieldset class="flex flex-col">
      <%= f.text_field :name, placeholder: "Category Name", required: true, class: "form-control rounded-0 shadow-none" %>
    <div class="flex gap-x-2 items-center shadow-none text-bold px-2 py-1 w-full border border-current">
        <%= f.label :add_icon, class: "form-control rounded-0" %>
        <i class="fa fa-caret-down text-blue" style="font-size:24px;"></i>
     </div>
    <%= f.file_field :icon, required: true, class: "form-control rounded-0 shadow-none w-full border border-current gap-2" %>
    <%= f.hidden_field :author_id, value: current_user.id %>
  </div>
    </fieldset>
  <% end %>
</div>

app/views/home/homepage.html.erb
<div class="container flex flex-col justify-between bg-slate-100 h-screen">
  <div class="basis-5/6 flex items-center justify-center">
    <h1 class=" container text-4xl text-center">BudgetApp</h1>
  </div>
  <div class="basis-1/6 flex flex-col justify-end">
    <%= link_to "Log In", new_user_session_path, class: "bg-blue text-white font-semibold text-center py-3 hover:bg-darkblue" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "bg-transparent font-semibold text-blue border border-blue text-center py-3 hover:bg-darkblue hover:text-white" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="w-full m-0">
    <%# <p class="notice"><%= notice</p> %>
    <%# <p class="alert"><%= alert</p>   %>
    <main class="lg:w-3/5 md:w-4/5 sm:w-full mx-auto">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <script>
      function toggleDropdown() {
      let dropdown = document.querySelector('.dropdown');
      dropdown.classList.toggle('show-dropdown');
      }
    </script>
  </body>
</html>

app/views/shared/_header.erb
<div class="dropdown">
  <button class="btn btn-outline border-0" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false" onclick="toggleDropdown()">
    <i class="fas fa-bars text-white py-1 bg-blue img" style="font-size:24px;"></i>
  </button>
  <ul class="dropdown-menu absolute z-10 left-4 pt-2 mt-2 w-32 bg-blue rounded-md shadow-lg" aria-labelledby="dropdownMenuButton1">
    <li><a class="block dropdown-item px-4 py-2 text-sm text-silver hover:bg-gray-100 hover:text-gray-900" href="/groups">Home</a></li>
    <li><%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item px-4 py-2 text-sm text-silver hover:text-start hover:bg-midnight hover:w-full hover:text-white" %></li>
  </ul>
</div>